# Generated by Django 4.2.16 on 2025-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "test"),
                            (2, "verification_email"),
                            (3, "forgot_password"),
                            (4, "review_completed"),
                            (5, "review_request"),
                            (6, "initial_cdi_values"),
                            (7, "download_geonode_dataset"),
                            (8, "new_user_password_setup"),
                            (9, "send_feedback"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "pending"),
                            (2, "on_progress"),
                            (3, "failed"),
                            (4, "done"),
                        ],
                        default=1,
                    ),
                ),
                ("attempt", models.IntegerField(default=0)),
                ("result", models.TextField(default=None, null=True)),
                ("info", models.JSONField(default=None, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("available", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "jobs",
            },
        ),
    ]
