version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:14-alpine
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./database/script:/script:ro
    environment:
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PASSWORD=password
      - DB_SCHEMA=dmh_app
      - DB_USER=akvo
    ports:
      - "5433:5432"
  backend:
    image: python:3.9
    working_dir: /app/backend
    command: ["./start.sh"]
    volumes:
      - ./:/app:delegated
      - ../.git:/app/.git:ro
    environment:
      - DB_SCHEMA=dmh_app
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - SECRET_KEY=secret
      - GEONODE_BASE_URL
      - GEONODE_HOST
      - GEONODE_ADMIN_USERNAME
      - GEONODE_ADMIN_PASSWORD
      - RUNDECK_API_URL
      - RUNDECK_API_TOKEN
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN:-}
      - CI_COMMIT=${CI_COMMIT:-}
      - CI_BRANCH=${CI_BRANCH:-}
      - CI_PULL_REQUEST=${CI_PULL_REQUEST:-}
      - GITHUB_SHA=${GITHUB_SHA:-}
      - GITHUB_REF=${GITHUB_REF:-}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-}
      - GITHUB_ACTOR=${GITHUB_ACTOR:-}
      - GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME:-}
      - GITHUB_RUN_ID=${GITHUB_RUN_ID:-}
      - GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER:-}
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=test@example.com
      - EMAIL_HOST_PASSWORD=password
      - EMAIL_FROM=test@example.com
      - WEBDOMAIN=notset
      - CSRF_TRUSTED_ORIGINS=https://example.com
      - SETUP_SECRET_KEY=secret
    depends_on:
      - db
  frontend:
    image: akvo/akvo-node-18-alpine:20230831.105309.b9593b7
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      - WEBDOMAIN=notset
      - SESSION_SECRET=secret
      - GEONODE_BASE_URL=http://localhost
      - SETUP_SECRET_KEY=secret
    depends_on:
      - backend
volumes:
  pg-data: