# Generated by Django 4.2.16 on 2025-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255, unique=True)),
                ("job_id", models.UUIDField()),
                ("job_config", models.JSONField(blank=True, null=True)),
                ("on_success_emails", models.JSONField(blank=True, null=True)),
                ("on_failure_emails", models.JSONField(blank=True, null=True)),
                ("on_exceeded_emails", models.JSONField(blank=True, null=True)),
                ("lst_weight", models.FloatField(default=0.3)),
                ("ndvi_weight", models.FloatField(default=0.3)),
                ("spi_weight", models.FloatField(default=0.4)),
                ("sm_weight", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "settings",
            },
        ),
    ]
