version: "3.8"
services:
  cdi:
    image: ifirmawan/cdi-scripts:latest
    container_name: cdi
    volumes:
      - input_data:/app/source/input_data
      - output_data:/app/source/output_data
      - ./config/cdi_directory_settings.json:/app/config/cdi_directory_settings.json
      - ./config/cdi_pattern_settings.json:/app/config/cdi_pattern_settings.json
      - ./config/cdi_project_settings.json:/app/config/cdi_project_settings.json
    working_dir: /app
    # Don't run the script immediately; let user exec into container
    command: ["sleep", "infinity"]

# In Production, use named volumes to persist data
volumes:
  input_data:
  output_data: